import type { LocalizedText, QuestionDifficulty } from "@/entities/question";
import { createRankedQuestion, rankingSources } from "../create-ranked-question";

const sources = [rankingSources.techprep, rankingSources.softwaretestpilot, rankingSources.coursera];
type Row = readonly [number, string, QuestionDifficulty, string, LocalizedText, LocalizedText, LocalizedText];
const categories: Record<string, LocalizedText> = {
  cicd: { ru: "CI/CD", en: "CI/CD" },
  performance: { ru: "Тестирование производительности", en: "Performance Testing" },
  security: { ru: "Тестирование безопасности", en: "Security Testing" },
  situational: { ru: "Ситуационные задачи", en: "Situational Testing" },
  integration: { ru: "Интеграционное тестирование", en: "Integration Testing" },
  "test-management": { ru: "Управление тестированием", en: "Test Management" },
  "quality-strategy": { ru: "Стратегия качества", en: "Quality Strategy" },
  observability: { ru: "Наблюдаемость", en: "Observability" },
  reliability: { ru: "Тестирование надёжности", en: "Reliability Testing" },
};
const rows: readonly Row[] = [
  [86,"automated-tests-in-ci","senior","cicd",{ru:"Как организовать автотесты в CI pipeline?",en:"How should automated tests be organized in a CI pipeline?"},{ru:"Быстрые детерминированные проверки запускают раньше, безопасно распараллеливают, изолируют данные и окружения, публикуют диагностику и оставляют дорогие наборы для подходящих этапов.",en:"Run fast deterministic checks early, parallelize safely, isolate data and environments, publish diagnostics, and reserve expensive suites for appropriate stages."},{ru:"автотесты в CI",en:"tests in CI"}],
  [87,"performance-testing","junior","performance",{ru:"Что такое тестирование производительности?",en:"What is performance testing?"},{ru:"Оно измеряет время ответа, пропускную способность, потребление ресурсов, масштабируемость и стабильность под заданной нагрузкой и целевыми показателями сервиса.",en:"It measures response time, throughput, resource use, scalability, and stability under defined workloads and service objectives."},{ru:"производительность",en:"performance"}],
  [88,"load-stress-spike-endurance","middle","performance",{ru:"Чем отличаются load, stress, spike и endurance testing?",en:"What are load, stress, spike, and endurance testing?"},{ru:"Load проверяет ожидаемую нагрузку, stress ищет пределы, spike — резкие изменения, а endurance выявляет деградацию при длительной работе.",en:"Load tests expected demand, stress finds limits, spike tests sudden changes, and endurance reveals degradation over sustained execution."},{ru:"нагрузочные виды",en:"performance test types"}],
  [89,"performance-metrics","middle","performance",{ru:"Какие метрики производительности важнее всего?",en:"Which performance metrics matter most?"},{ru:"Используют перцентили задержки, throughput, error rate, saturation, ресурсы, глубину очередей и бизнес-успех, сопоставляя метрики разных слоёв.",en:"Use latency percentiles, throughput, error rate, saturation, resource use, queue depth, and business success metrics correlated across layers."},{ru:"метрики производительности",en:"performance metrics"}],
  [90,"owasp-security-risks","middle","security",{ru:"Что такое security testing и что QA должен знать об OWASP-рисках?",en:"What is security testing and what should QA know about OWASP risks?"},{ru:"QA должен понимать проверки контроля доступа, injection, аутентификации, утечек данных, конфигурации, уязвимых компонентов, логирования и server-side request risks.",en:"QA should understand checks for access control, injection, authentication, data exposure, configuration, vulnerable components, logging, and server-side request risks."},{ru:"OWASP",en:"OWASP"}],
  [91,"authorization-access-control","senior","security",{ru:"Как тестировать авторизацию и контроль доступа?",en:"How do you test authorization and access control?"},{ru:"Строят матрицу субъект–ресурс–действие и проверяют вертикальное и горизонтальное повышение привилегий, прямые ссылки на объекты, default deny, изменения сессии и аудит.",en:"Build an actor-resource-action matrix and test vertical and horizontal privilege escalation, direct object references, default denial, session changes, and audit evidence."},{ru:"контроль доступа",en:"access control"}],
  [92,"sql-injection-testing","middle","security",{ru:"Что такое SQL injection и как безопасно её тестировать?",en:"What is SQL injection and how can it be tested safely?"},{ru:"SQL injection возникает, когда недоверенный ввод меняет структуру запроса; проверять её нужно только в разрешённом окружении контролируемыми payloads, оценивая параметризацию и обработку ошибок.",en:"SQL injection occurs when untrusted input changes query structure; test only in authorized environments using controlled payloads and verify parameterization and error handling."},{ru:"SQL injection",en:"SQL injection"}],
  [93,"xss-and-csrf","middle","security",{ru:"Что такое XSS и CSRF?",en:"What are XSS and CSRF?"},{ru:"XSS выполняет контролируемый атакующим скрипт в доверенном origin, а CSRF заставляет браузер отправить нежелательный аутентифицированный запрос; защиты различаются.",en:"XSS executes attacker-controlled script in a trusted origin, while CSRF causes a browser to send an unwanted authenticated request; their mitigations differ."},{ru:"XSS и CSRF",en:"XSS and CSRF"}],
  [94,"critical-production-defect","senior","situational",{ru:"Как действовать при критическом дефекте в production?",en:"How do you handle a critical production defect?"},{ru:"Нужно ограничить влияние, собрать факты, прозрачно сообщать статус, поддержать rollback или mitigation, безопасно воспроизвести, найти причину, проверить исправление и добавить профилактику.",en:"Stabilize impact, collect evidence, communicate clearly, support rollback or mitigation, reproduce safely, identify root cause, verify the fix, and add preventive controls."},{ru:"production defect",en:"production defect"}],
  [95,"developer-says-not-a-bug","middle","situational",{ru:"Что делать, если разработчик считает найденную проблему не багом?",en:"What do you do when a developer says a reported issue is not a bug?"},{ru:"Нужно согласовать требования, влияние на пользователя, доказательства и риск, а не спорить о термине; при неоднозначности подключить product или design.",en:"Align on requirements, user impact, evidence, and risk rather than labels; involve product or design when behavior is intentionally ambiguous."},{ru:"коммуникация о дефекте",en:"defect communication"}],
  [96,"tight-deadline-testing","senior","situational",{ru:"Как тестировать при очень ограниченном времени?",en:"How do you test under a very tight deadline?"},{ru:"Явно фиксируют риски, сначала покрывают критические пользовательские и data paths, выбирают быстрые доказательства, сообщают пропуски, добавляют мониторинг и планируют последующие проверки.",en:"Make risk assumptions explicit, cover critical user and data paths first, choose fast evidence, communicate omissions, add monitoring, and plan follow-up testing."},{ru:"ограниченное время",en:"tight deadline"}],
  [97,"non-reproducible-defect","middle","situational",{ru:"Как исследовать дефект, который не удаётся воспроизвести?",en:"How do you investigate a defect that cannot be reproduced?"},{ru:"Собирают окружение, данные, время, логи, traces, видео, feature flags и контекст конкурентности, сравнивают различия и улучшают наблюдаемость вместо преждевременного закрытия.",en:"Collect environment, data, timestamps, logs, traces, video, feature flags, and concurrency context; compare differences and improve observability instead of closing prematurely."},{ru:"невоспроизводимый дефект",en:"non-reproducible defect"}],
  [98,"external-dependencies-testing","senior","integration",{ru:"Как тестировать функцию с множеством внешних зависимостей?",en:"How do you test a feature with many external dependencies?"},{ru:"Описывают контракты и режимы отказа, выборочно применяют stubs и service virtualization, проверяют реальные интеграции и тестируют таймауты, повторы, fallback и наблюдаемость.",en:"Map contracts and failure modes, use stubs and service virtualization selectively, verify real integrations, and test timeouts, retries, fallbacks, and observability."},{ru:"внешние зависимости",en:"external dependencies"}],
  [99,"measure-test-effectiveness","senior","test-management",{ru:"Как измерять эффективность тестирования?",en:"How do you measure test effectiveness?"},{ru:"Используют outcome-метрики: пропущенный риск, момент обнаружения, change failure rate, надёжность набора, время обратной связи, покрытие критических рисков и обучение на инцидентах.",en:"Use outcome-oriented signals such as escaped risk, detection timing, change failure rate, suite reliability, feedback time, critical-risk coverage, and incident learning."},{ru:"эффективность тестирования",en:"test effectiveness"}],
  [100,"shift-left-shift-right","senior","quality-strategy",{ru:"Что такое shift-left и shift-right testing?",en:"What are shift-left and shift-right testing?"},{ru:"Shift-left переносит обратную связь раньше через тестируемость и профилактику, а shift-right использует production-наблюдаемость, эксперименты, resilience checks и пользовательские данные.",en:"Shift-left moves feedback earlier through testability and prevention; shift-right learns from production using observability, experiments, resilience checks, and user evidence."},{ru:"shift-left и shift-right",en:"shift-left and shift-right"}],
];

export const top100Batch086100 = rows.map(([rank,slug,difficulty,categorySlug,title,summary,label]) => createRankedQuestion({ rank, slug, difficulty, categorySlug, category: categories[categorySlug]!, title, summary, tags: [{ key: slug, label }], sources }));
