import type { LocalizedText, QuestionDifficulty } from "@/entities/question";
import { createRankedQuestion, rankingSources } from "../create-ranked-question";

const sources = [rankingSources.techprep, rankingSources.kiran, rankingSources.enigma];
type Row = readonly [number, string, QuestionDifficulty, string, LocalizedText, LocalizedText, LocalizedText];
const categories: Record<string, LocalizedText> = {
  "testing-types": { ru: "Виды тестирования", en: "Testing Types" },
  "testing-levels": { ru: "Уровни тестирования", en: "Testing Levels" },
  "testing-approaches": { ru: "Подходы к тестированию", en: "Testing Approaches" },
  processes: { ru: "Процессы", en: "Processes" },
  "test-management": { ru: "Управление тестированием", en: "Test Management" },
  requirements: { ru: "Требования", en: "Requirements" },
  agile: { ru: "Agile и Scrum", en: "Agile and Scrum" },
  situational: { ru: "Ситуационные задачи", en: "Situational Testing" },
};
const rows: readonly Row[] = [
  [26,"functional-vs-non-functional","junior","testing-types",{ru:"Чем отличаются функциональное и нефункциональное тестирование?",en:"What is the difference between functional and non-functional testing?"},{ru:"Функциональное тестирование проверяет поведение и бизнес-функции, а нефункциональное — производительность, безопасность, удобство, доступность и надёжность.",en:"Functional testing checks behavior and business functions; non-functional testing evaluates performance, security, usability, accessibility, and reliability."},{ru:"функциональность",en:"functionality"}],
  [27,"testing-levels","junior","testing-levels",{ru:"Что такое модульное, интеграционное, системное и приёмочное тестирование?",en:"What are unit, integration, system, and acceptance testing levels?"},{ru:"Уровни последовательно проверяют отдельные компоненты, их взаимодействие, систему целиком и соответствие бизнес-критериям приёмки.",en:"The levels progressively verify isolated components, their interactions, the complete system, and business acceptance criteria."},{ru:"уровни тестирования",en:"testing levels"}],
  [28,"black-white-gray-box","junior","testing-approaches",{ru:"Что такое black-box, white-box и gray-box тестирование?",en:"What are black-box, white-box, and gray-box testing?"},{ru:"Black-box опирается на внешнее поведение, white-box — на знание реализации, а gray-box сочетает частичное внутреннее знание с пользовательскими проверками.",en:"Black-box uses external behavior, white-box uses implementation knowledge, and gray-box combines partial internal knowledge with user-facing checks."},{ru:"подходы",en:"testing approaches"}],
  [29,"static-testing","junior","testing-types",{ru:"Что такое статическое тестирование?",en:"What is static testing?"},{ru:"Статическое тестирование анализирует требования, дизайн, код и другие артефакты без запуска программы — через ревью и инструменты анализа.",en:"Static testing examines requirements, design, code, and other artifacts without executing the software through reviews and analysis tools."},{ru:"статический анализ",en:"static analysis"}],
  [30,"sdlc-vs-stlc","junior","processes",{ru:"Чем отличаются SDLC и STLC?",en:"What is the difference between SDLC and STLC?"},{ru:"SDLC охватывает весь жизненный цикл разработки продукта, а STLC структурирует тестирование от анализа требований до завершения и отчётности.",en:"SDLC covers the entire product development lifecycle; STLC structures testing from requirements analysis through closure and reporting."},{ru:"жизненный цикл",en:"lifecycle"}],
  [31,"entry-exit-criteria","junior","test-management",{ru:"Что такое критерии входа и выхода в тестировании?",en:"What are entry and exit criteria in testing?"},{ru:"Критерии входа определяют готовность к началу проверки, а критерии выхода — достаточность доказательств и приемлемость остаточного риска.",en:"Entry criteria define readiness to begin testing; exit criteria define sufficient evidence and acceptable residual risk."},{ru:"критерии",en:"criteria"}],
  [32,"test-plan","junior","test-management",{ru:"Что такое тест-план и что в него входит?",en:"What is a test plan and what should it include?"},{ru:"Тест-план фиксирует объём, цели, риски, подход, окружения, данные, ответственность, сроки, результаты и критерии завершения.",en:"A test plan records scope, objectives, risks, approach, environments, data, responsibilities, schedule, deliverables, and completion criteria."},{ru:"тест-план",en:"test plan"}],
  [33,"requirements-traceability-matrix","junior","requirements",{ru:"Что такое матрица трассируемости требований?",en:"What is a requirements traceability matrix?"},{ru:"Матрица связывает требования с тестами и дефектами, помогает видеть пробелы покрытия и оценивать влияние изменений.",en:"The matrix links requirements to tests and defects, revealing coverage gaps and supporting change-impact analysis."},{ru:"трассируемость",en:"traceability"}],
  [34,"unclear-requirements","middle","requirements",{ru:"Как тестировать неполные или неоднозначные требования?",en:"How do you test unclear or incomplete requirements?"},{ru:"Нужно выявить допущения и противоречия, запросить конкретные примеры, зафиксировать решения и проверять наблюдаемые бизнес-правила, не подменяя требования догадками.",en:"Identify assumptions and contradictions, request concrete examples, record decisions, and test observable business rules instead of silently guessing."},{ru:"неоднозначные требования",en:"ambiguous requirements"}],
  [35,"requirements-testability","middle","requirements",{ru:"Как оценить требования на тестируемость?",en:"How do you review requirements for testability?"},{ru:"Требования должны быть однозначными, измеримыми, непротиворечивыми, реализуемыми, трассируемыми и содержать явные ограничения и критерии приёмки.",en:"Requirements should be unambiguous, measurable, consistent, feasible, traceable, and explicit about constraints and acceptance criteria."},{ru:"тестируемость",en:"testability"}],
  [36,"agile-testing","junior","agile",{ru:"Что такое тестирование в Agile?",en:"What is Agile testing?"},{ru:"Это непрерывная совместная работа над качеством внутри коротких циклов поставки, с ранней обратной связью и общей ответственностью команды.",en:"It is continuous collaborative quality work inside short delivery cycles with early feedback and shared team ownership."},{ru:"Agile",en:"Agile"}],
  [37,"qa-in-scrum-ceremonies","junior","agile",{ru:"Какова роль QA на церемониях Scrum?",en:"What is the QA role in Scrum ceremonies?"},{ru:"QA поднимает риски и тестируемость на refinement и planning, сообщает блокеры на daily, предоставляет доказательства на review и улучшает процесс на retrospective.",en:"QA raises risks and testability in refinement and planning, reports blockers at daily meetings, provides evidence in reviews, and improves the process in retrospectives."},{ru:"Scrum",en:"Scrum"}],
  [38,"definition-of-done","middle","agile",{ru:"Что такое Definition of Done и как QA участвует в её формировании?",en:"What is Definition of Done and how does QA contribute?"},{ru:"Definition of Done — общий контракт качества; QA помогает явно определить приёмку, проверки, автоматизацию, документацию и наблюдаемость.",en:"Definition of Done is a shared quality contract; QA helps define acceptance, testing, automation, documentation, and observability expectations."},{ru:"Definition of Done",en:"Definition of Done"}],
  [39,"estimate-testing-work","middle","test-management",{ru:"Как оценивать трудозатраты на тестирование?",en:"How do you estimate testing work?"},{ru:"Оценка учитывает объём, риск, сложность, зависимости, окружения, данные, регрессию и неопределённость и пересматривается по мере появления фактов.",en:"Estimate using scope, risk, complexity, dependencies, environments, data, regression impact, and uncertainty, then revise as evidence changes."},{ru:"оценка",en:"estimation"}],
  [40,"when-testing-is-enough","middle","test-management",{ru:"Как понять, что тестирования достаточно?",en:"How do you decide when testing is enough?"},{ru:"Тестирование достаточно, когда выполнены согласованные критерии покрытия и выхода, а остаточный риск понятен и принят ответственными за решение.",en:"Testing is enough when agreed coverage and exit criteria are met and remaining risk is understood and accepted by decision makers."},{ru:"остаточный риск",en:"residual risk"}],
  [41,"prioritize-test-cases","middle","test-management",{ru:"Как приоритизировать тест-кейсы?",en:"How do you prioritize test cases?"},{ru:"Приоритет определяют влияние на пользователя и бизнес, объём изменений, вероятность отказа, частота использования, зависимости и стоимость восстановления.",en:"Prioritize by user and business impact, change scope, failure likelihood, usage frequency, dependencies, and recovery cost."},{ru:"приоритизация",en:"prioritization"}],
  [42,"test-login-form","junior","situational",{ru:"Как тестировать форму входа?",en:"How do you test a login form?"},{ru:"Проверяют валидные и невалидные данные, границы полей, валидацию, сессии, блокировку, восстановление, безопасность, доступность и локализацию.",en:"Cover valid and invalid credentials, field boundaries, validation, sessions, lockout, recovery, security, accessibility, and localization."},{ru:"форма входа",en:"login form"}],
  [43,"test-search-field","junior","situational",{ru:"Как тестировать поле поиска?",en:"How do you test a search field?"},{ru:"Проверяют точные и частичные совпадения, нормализацию, пустые и специальные данные, ранжирование, фильтры, пагинацию, производительность и состояние без результатов.",en:"Test exact and partial matches, normalization, empty and special input, ranking, filters, pagination, performance, and no-result behavior."},{ru:"поиск",en:"search"}],
  [44,"test-checkout","middle","situational",{ru:"Как тестировать оформление заказа в интернет-магазине?",en:"How do you test an e-commerce checkout?"},{ru:"Нужно покрыть корзину, цены, скидки, остатки, адрес, оплату, повторы, идемпотентность, подтверждение, отмену, возвраты и восстановление после ошибок.",en:"Cover cart, pricing, promotions, inventory, address, payment, retries, idempotency, confirmation, cancellation, refunds, and failure recovery."},{ru:"checkout",en:"checkout"}],
  [45,"test-file-upload","middle","situational",{ru:"Как тестировать загрузку файлов?",en:"How do you test a file upload feature?"},{ru:"Проверяют форматы, размер и количество, имена и кодировки, прерывания, права, вредоносный контент, сбои хранилища, превью и доступность.",en:"Verify formats, size and count limits, names and encodings, interrupted uploads, permissions, malicious content controls, storage failures, previews, and accessibility."},{ru:"загрузка файлов",en:"file upload"}],
];

export const top100Batch026045 = rows.map(([rank,slug,difficulty,categorySlug,title,summary,label]) => createRankedQuestion({ rank, slug, difficulty, categorySlug, category: categories[categorySlug]!, title, summary, tags: [{ key: slug, label }], sources }));
