import { createRankedQuestion, rankingSources } from "../create-ranked-question";

const sources = [rankingSources.katalon, rankingSources.indeed, rankingSources.yandex];
const c = {
  fundamentals: { ru: "Основы тестирования", en: "Testing Fundamentals" },
  documentation: { ru: "Тестовая документация", en: "Test Documentation" },
  defects: { ru: "Управление дефектами", en: "Defect Management" },
  types: { ru: "Виды тестирования", en: "Testing Types" },
  design: { ru: "Тест-дизайн", en: "Test Design" },
  approaches: { ru: "Подходы к тестированию", en: "Testing Approaches" },
} as const;
const tag = (key: string, ru: string, en: string) => [{ key, label: { ru, en } }];

export const top100Batch007025 = [
  createRankedQuestion({
    rank: 7,
    slug: "software-testing-purpose",
    difficulty: "junior",
    categorySlug: "testing-fundamentals",
    category: c.fundamentals,
    title: {
      ru: "Что такое тестирование ПО и зачем оно нужно?",
      en: "What is software testing and why is it necessary?",
    },
    summary: {
      ru: "Тестирование оценивает продукт относительно требований и рисков, выявляет дефекты и даёт данные для решений о релизе.",
      en: "Testing evaluates a product against requirements and risks, reveals defects, and provides evidence for release decisions.",
    },
    tags: tag("testing-purpose", "цели тестирования", "testing purpose"),
    sources,
  }),
  createRankedQuestion({
    rank: 8,
    slug: "qa-qc-testing-difference",
    difficulty: "junior",
    categorySlug: "testing-fundamentals",
    category: c.fundamentals,
    title: {
      ru: "Чем отличаются QA, QC и тестирование?",
      en: "What is the difference between QA, QC, and testing?",
    },
    summary: {
      ru: "QA улучшает процессы, QC оценивает качество продукта, а тестирование является одной из проверочных активностей контроля качества.",
      en: "QA improves processes, QC evaluates product quality, and testing is a verification activity within quality control.",
    },
    tags: tag("qa-qc", "QA и QC", "QA and QC"),
    sources,
  }),
  createRankedQuestion({
    rank: 9,
    slug: "verification-vs-validation",
    difficulty: "junior",
    categorySlug: "testing-fundamentals",
    category: c.fundamentals,
    title: {
      ru: "Чем отличаются верификация и валидация?",
      en: "What is the difference between verification and validation?",
    },
    summary: {
      ru: "Верификация проверяет соответствие спецификациям, а валидация — решает ли продукт реальную задачу пользователя.",
      en: "Verification checks conformance to specifications; validation checks whether the product solves the user's real need.",
    },
    tags: tag("verification-validation", "верификация и валидация", "verification and validation"),
    sources,
  }),
  createRankedQuestion({
    rank: 10,
    slug: "testing-principles",
    difficulty: "junior",
    categorySlug: "testing-fundamentals",
    category: c.fundamentals,
    title: {
      ru: "Каковы основные принципы тестирования ПО?",
      en: "What are the main principles of software testing?",
    },
    summary: {
      ru: "К принципам относятся невозможность исчерпывающей проверки, раннее тестирование, кластеризация дефектов, зависимость от контекста и парадокс пестицида.",
      en: "Principles include exhaustive testing being impossible, early testing, defect clustering, context dependence, and the pesticide paradox.",
    },
    tags: tag("testing-principles", "принципы тестирования", "testing principles"),
    sources,
  }),
  createRankedQuestion({
    rank: 11,
    slug: "test-case-checklist-scenario",
    difficulty: "junior",
    categorySlug: "test-documentation",
    category: c.documentation,
    title: {
      ru: "Чем отличаются тест-кейс, чек-лист и тестовый сценарий?",
      en: "What is the difference between a test case, checklist, and test scenario?",
    },
    summary: {
      ru: "Сценарий описывает цель проверки, чек-лист содержит краткие пункты, а тест-кейс фиксирует предусловия, шаги, данные и ожидаемый результат.",
      en: "A scenario states the testing goal, a checklist lists concise checks, and a test case defines preconditions, steps, data, and expected results.",
    },
    tags: tag("test-artifacts", "тестовые артефакты", "test artifacts"),
    sources,
  }),
  createRankedQuestion({
    rank: 12,
    slug: "good-test-case",
    difficulty: "junior",
    categorySlug: "test-documentation",
    category: c.documentation,
    title: { ru: "Каким должен быть хороший тест-кейс?", en: "What makes a good test case?" },
    summary: {
      ru: "Хороший тест-кейс понятен, атомарен, воспроизводим, связан с риском или требованием и явно описывает данные и ожидаемый результат.",
      en: "A good test case is clear, atomic, reproducible, traceable to risk or requirements, and explicit about data and expected outcomes.",
    },
    tags: tag("test-case-quality", "качество тест-кейсов", "test case quality"),
    sources,
  }),
  createRankedQuestion({
    rank: 13,
    slug: "good-bug-report",
    difficulty: "junior",
    categorySlug: "defect-management",
    category: c.defects,
    title: {
      ru: "Что должен содержать качественный баг-репорт?",
      en: "What should a high-quality bug report contain?",
    },
    summary: {
      ru: "Баг-репорт содержит краткий заголовок, окружение, предусловия, точные шаги, фактический и ожидаемый результат, серьёзность, доказательства и воспроизводимость.",
      en: "A bug report contains a concise title, environment, preconditions, exact steps, actual and expected results, severity, evidence, and reproducibility.",
    },
    tags: tag("bug-report", "баг-репорт", "bug report"),
    sources,
  }),
  createRankedQuestion({
    rank: 14,
    slug: "severity-vs-priority",
    difficulty: "junior",
    categorySlug: "defect-management",
    category: c.defects,
    title: {
      ru: "Чем отличаются severity и priority?",
      en: "What is the difference between severity and priority?",
    },
    summary: {
      ru: "Severity описывает влияние дефекта, а priority — насколько срочно бизнесу или команде требуется исправление.",
      en: "Severity describes defect impact; priority describes how urgently the business or team needs a fix.",
    },
    tags: tag("severity-priority", "серьёзность и приоритет", "severity and priority"),
    sources,
  }),
  createRankedQuestion({
    rank: 15,
    slug: "defect-life-cycle",
    difficulty: "junior",
    categorySlug: "defect-management",
    category: c.defects,
    title: { ru: "Что такое жизненный цикл дефекта?", en: "What is the defect life cycle?" },
    summary: {
      ru: "Дефект проходит регистрацию, триаж, назначение, исправление, ретест и закрытие либо переоткрытие; конкретный workflow зависит от команды.",
      en: "A defect moves through reporting, triage, assignment, fixing, retesting, and closure or reopening, with workflow variations by team.",
    },
    tags: tag("defect-lifecycle", "жизненный цикл дефекта", "defect lifecycle"),
    sources,
  }),
  createRankedQuestion({
    rank: 16,
    slug: "regression-testing",
    difficulty: "junior",
    categorySlug: "testing-types",
    category: c.types,
    title: {
      ru: "Что такое регрессионное тестирование и когда его проводить?",
      en: "What is regression testing and when should it be performed?",
    },
    summary: {
      ru: "Регрессия проверяет, что изменения не сломали ранее работавшее поведение; объём выбирают по масштабу изменений и риску.",
      en: "Regression testing checks that changes did not break previously working behavior; scope is selected by change impact and risk.",
    },
    tags: tag("regression", "регрессия", "regression"),
    sources,
  }),
  createRankedQuestion({
    rank: 17,
    slug: "retesting-vs-regression",
    difficulty: "junior",
    categorySlug: "testing-types",
    category: c.types,
    title: {
      ru: "Чем отличаются ретест и регрессия?",
      en: "What is the difference between retesting and regression testing?",
    },
    summary: {
      ru: "Ретест подтверждает конкретное исправление, а регрессия проверяет соседнее и ранее стабильное поведение на побочные эффекты.",
      en: "Retesting confirms a specific fix, while regression testing checks surrounding and previously stable behavior for unintended effects.",
    },
    tags: tag("retest-regression", "ретест и регрессия", "retest and regression"),
    sources,
  }),
  createRankedQuestion({
    rank: 18,
    slug: "smoke-vs-sanity",
    difficulty: "junior",
    categorySlug: "testing-types",
    category: c.types,
    title: {
      ru: "Что такое smoke- и sanity-тестирование?",
      en: "What are smoke and sanity testing?",
    },
    summary: {
      ru: "Smoke подтверждает общую пригодность сборки к проверке, а sanity быстро оценивает конкретную изменённую область.",
      en: "Smoke testing verifies that a build is broadly testable; sanity testing narrowly checks a changed area.",
    },
    tags: tag("smoke-sanity", "smoke и sanity", "smoke and sanity"),
    sources,
  }),
  createRankedQuestion({
    rank: 19,
    slug: "positive-negative-testing",
    difficulty: "junior",
    categorySlug: "test-design",
    category: c.design,
    title: {
      ru: "Что такое позитивное и негативное тестирование?",
      en: "What are positive and negative testing?",
    },
    summary: {
      ru: "Позитивные тесты используют валидные данные и ожидаемые сценарии, а негативные проверяют валидацию, ошибки, ограничения и недопустимые состояния.",
      en: "Positive tests use valid data and expected flows; negative tests challenge validation, errors, limits, and invalid states.",
    },
    tags: tag(
      "positive-negative",
      "позитивные и негативные проверки",
      "positive and negative checks",
    ),
    sources,
  }),
  createRankedQuestion({
    rank: 20,
    slug: "equivalence-partitioning",
    difficulty: "junior",
    categorySlug: "test-design",
    category: c.design,
    title: { ru: "Что такое классы эквивалентности?", en: "What is equivalence partitioning?" },
    summary: {
      ru: "Техника делит данные или состояния на группы с одинаковым ожидаемым поведением, чтобы проверять репрезентативные значения.",
      en: "The technique divides data or states into groups expected to behave similarly so representative values can cover each class.",
    },
    tags: tag("equivalence-classes", "классы эквивалентности", "equivalence classes"),
    sources,
  }),
  createRankedQuestion({
    rank: 21,
    slug: "boundary-value-analysis",
    difficulty: "junior",
    categorySlug: "test-design",
    category: c.design,
    title: { ru: "Что такое анализ граничных значений?", en: "What is boundary value analysis?" },
    summary: {
      ru: "Техника проверяет значения на границе и рядом с ней, поскольку ошибки часто возникают в точках перехода.",
      en: "The technique targets values at and around limits because implementation errors frequently occur at transitions.",
    },
    tags: tag("boundary-values", "граничные значения", "boundary values"),
    sources,
  }),
  createRankedQuestion({
    rank: 22,
    slug: "decision-table-testing",
    difficulty: "junior",
    categorySlug: "test-design",
    category: c.design,
    title: {
      ru: "Что такое таблица решений и когда она полезна?",
      en: "What is a decision table and when is it useful?",
    },
    summary: {
      ru: "Таблица решений связывает комбинации условий с действиями и полезна для бизнес-правил с взаимодействующими входами.",
      en: "A decision table maps combinations of conditions to actions and is useful for business rules with interacting inputs.",
    },
    tags: tag("decision-table", "таблица решений", "decision table"),
    sources,
  }),
  createRankedQuestion({
    rank: 23,
    slug: "state-transition-testing",
    difficulty: "junior",
    categorySlug: "test-design",
    category: c.design,
    title: {
      ru: "Что такое тестирование переходов состояний?",
      en: "What is state transition testing?",
    },
    summary: {
      ru: "Техника проверяет допустимые и недопустимые события, переходы между состояниями и результирующие действия.",
      en: "The technique verifies valid and invalid events, transitions between states, and resulting actions.",
    },
    tags: tag("state-transitions", "переходы состояний", "state transitions"),
    sources,
  }),
  createRankedQuestion({
    rank: 24,
    slug: "exploratory-testing",
    difficulty: "junior",
    categorySlug: "testing-approaches",
    category: c.approaches,
    title: { ru: "Что такое исследовательское тестирование?", en: "What is exploratory testing?" },
    summary: {
      ru: "Исследовательское тестирование объединяет обучение, проектирование и выполнение проверок в ограниченной по времени сессии, направляемой чартером.",
      en: "Exploratory testing combines learning, test design, and execution in a time-boxed session guided by a charter.",
    },
    tags: tag("exploratory", "исследовательское тестирование", "exploratory testing"),
    sources,
  }),
  createRankedQuestion({
    rank: 25,
    slug: "ad-hoc-vs-exploratory",
    difficulty: "junior",
    categorySlug: "testing-approaches",
    category: c.approaches,
    title: {
      ru: "Чем ad hoc тестирование отличается от исследовательского?",
      en: "How does ad hoc testing differ from exploratory testing?",
    },
    summary: {
      ru: "Ad hoc почти не структурировано, а исследовательское тестирование имеет цель, ограничение по времени и фиксирует наблюдения и выводы.",
      en: "Ad hoc testing is minimally structured, while exploratory testing is goal-driven, time-boxed, and records observations and conclusions.",
    },
    tags: tag("ad-hoc", "ad hoc", "ad hoc"),
    sources,
  }),
] as const;
